#!/bin/bash
# This script copies selected programs, libraries and their dependencies from 
# the Entware-NG installation folder and then changes the library root folder 
# from /opt to /entware, so that the programs may be compiled directly into the 
# Asuswrt-Merlin firmware.  It requires an Entware-NG build environment with 
# all selected packages pre-compiled.

#cd $HOME/blackfuel
#ln -sf ../asuswrt-merlin-addon asuswrt-merlin-addon
ADDON_FOLDER="$HOME/blackfuel/asuswrt-merlin-addon"
ADDON_STAGING_FOLDER="$ADDON_FOLDER/staging"
ADDON_STAGING_ENTWARE_FOLDER="$ADDON_STAGING_FOLDER/entware"
ENTWARE_NETWORK="//192.168.234.133/entware-ng"
ENTWARE_FOLDER="$HOME/Entware-ng"
ENTWARE_INSTALL_FOLDER="$ENTWARE_FOLDER/staging_dir/target-arm_cortex-a9_glibc-2.23_eabi/root-armv7soft/opt"

$HOME/blackfuel/asuswrt-merlin-tools/install attach
$HOME/blackfuel/asuswrt-merlin-tools/cp attach

# connect to the Entware-NG build machine
if [ ! -d "$ENTWARE_INSTALL_FOLDER" ]; then
  mkdir -p $ENTWARE_FOLDER
  sudo mount -t cifs -o user=guest $ENTWARE_NETWORK $ENTWARE_FOLDER

  if [ ! -d "$ENTWARE_INSTALL_FOLDER" ]; then
    exit 1
  fi
fi

# copy selected programs, libraries and their dependencies from Entware-NG
mkdir -p $ADDON_STAGING_FOLDER
cd $ADDON_STAGING_FOLDER
rm -rf $ADDON_STAGING_ENTWARE_FOLDER
mkdir -p sbin
cd sbin
ln -s /entware/sbin/dmsetup dmsetup

cd $ADDON_FOLDER
declare -A LIB_HASH
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/lib/libnss_dns.so.2
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/lib/libnss_files.so.2
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/base64
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/bzip2
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/cksum
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/curl
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/dos2unix
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/esniper
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/find
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/hostip
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/htop
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/iostat
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/lsblk
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/lsof
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/md5sum
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/objcopy
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/objdump
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/openssl
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/readelf
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/rsync
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/sha1sum
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/sha224sum
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/sha256sum
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/sha384sum
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/sha512sum
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/stat
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/tftp-hpa
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/strip
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/stty
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/sum
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/tar
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/unix2dos
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/unrar
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/unzip
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/unzipfx
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/uuidgen
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/whoami
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/xxd
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/bin/zip
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/blkdeactivate
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/dmsetup
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/dmstats
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/fsadm
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/apcaccess
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/apctest
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/apcupsd
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/cryptsetup
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/fallocate
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/fdformat
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/hexdump
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/ldattach
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/losetup
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/lvchange
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/lvconvert
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/lvcreate
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/lvdisplay
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/lvextend
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/lvmchange
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/lvmconf
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/lvmconfig
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/lvmdiskscan
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/lvmdump
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/lvmsadc
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/lvmsar
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/lvreduce
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/lvremove
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/lvrename
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/lvresize
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/lvs
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/lvscan
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/privoxy
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/pvchange
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/pvck
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/pvcreate
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/pvdisplay
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/pvmove
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/pvremove
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/pvresize
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/pvs
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/pvscan
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/screen
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/tcpdump
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/tftpd-hpa
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/uuidd
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/veritysetup
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/vgcfgbackup
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/vgcfgrestore
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/vgchange
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/vgck
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/vgconvert
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/vgcreate
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/vgdisplay
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/vgexport
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/vgextend
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/vgimport
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/vgimportclone
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/vgmerge
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/vgmknodes
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/vgreduce
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/vgremove
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/vgrename
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/vgs
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/vgscan
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/vgsplit
source $ADDON_FOLDER/cp-entware $ENTWARE_INSTALL_FOLDER/sbin/whois
chmod -R 0755 $ADDON_STAGING_FOLDER/*

# disconnect from the Entware-NG build machine
sudo umount $ENTWARE_FOLDER


# set file permissions
cd $ADDON_STAGING_FOLDER/sbin
chmod u=rx,g=,o= halt reboot

$HOME/blackfuel/asuswrt-merlin-tools/install detach
$HOME/blackfuel/asuswrt-merlin-tools/cp detach
